### ISSUE TITLE
Name of named service is not clickable and suggestable

### ISSUE THREAD

**Issue by lulco** [mesour-intellij-plugins/neon-nette-issues#14]
I have modular system based on multiple configs. In one config (core) I register service with some name (plugins in example below):
```
services:
    plugins:
        factory: Efabrica\Cms\Core\Plugin\PluginsContainer
```
Then in modules, I register Plugin classes to PluginsContainer:
```
services:
    plugins:
        setup:
            - registerPlugin(Efabrica\Cms\Foo\Plugin\BarPlugin())
```

*Problem 1:*
When I'm writing:
```
services:
    plugins:
```
I would like to have "plugins" (and all names of services) in suggestions. Now there are only classes. Class names should be suggested only if `-` is used before.

*Problem 2:*
I can't jump to the place where the service is registered and / or used.

PS: I would like to thank for feature which works already - suggestion of method `registerPlugin` in setup.
