### ISSUE TITLE
Problem with completion if named services is defined without sub keys

### ISSUE THREAD

**Issue by mesour** [mesour-intellij-plugins/neon-nette-issues#17]
Not working:

```
services:
    test: Foo\Bar

foo: @test::<NOTHING>
```

This works:

```
services:
    test:
        factory: Foo\Bar

foo: @test::<NOTHING>
```
