### ISSUE TITLE
Plugin ignores (partial) namespace before cursor

### ISSUE THREAD

**Issue by lulco** [mesour-intellij-plugins/neon-nette-issues#25]
**Describe the bug**
I have this neon:
```
services:
    myTaskManager:
        setup:
            - addTask(Task\FirstTask())
            - addTask(Task\())
```

If I hit ctrl+space after `Task\` in second row of setup, result will be `Task\Task\SecondTask` - so plugin ignores already written namespace and adds full class name here.

This bug doesn't occure in service registration e.g.:
```
services:
    - Task\FirstTask()
    - Task\
```
After hitting ctrl+space everything is OK.

**Environment (please complete the following information):**
 - PhpStorm version [e.g. 2021.2.3]
 - Plugin version [e.g. 1.0.3]
